### ISSUE TITLE
Plugin resetting configuration

### ISSUE THREAD

**Issue by ghost** [Imanity-Software/iSpigot-PracticeAddon#1]
**Plugin version:** 2.1
**iSpigot version:** 2.2-SNAPSHOT
**iSpigot launcher:** 2.4.0b1
**Practice plugin:** StrikePractice 3.3.2
**Problem:**

It seems like the plugin just loads it's default configuration no matter what, 
even after configuring without making an error. I have tested 2.1 and 2.0
The plugin otherwise loads just fine and detects StrikePractice being used

**Update:** Tested 1.0 version of the plugin, seems to be keeping the edited config but actual functionality not tested yet

**Update 2:** 1.0 with SP 3.3.2 and iSpigot 2.2 is erroring DuelStartEvent and RoundStartEvent which I'm guessing are fixed in the latest version of the plugin, however that one always resets the config on server restart (original problem)

**Comment by ferencKx** [comment]
**Update:** Tested 1.0 version of the plugin, seems to be keeping the edited config but actual functionality not tested yet

**Comment by ferencKx** [comment]
**Update 2:** 1.0 with SP 3.3.2 and iSpigot 2.2 is erroring DuelStartEvent and RoundStartEvent which I'm guessing are fixed in the latest version of the plugin, however that one always resets the config on server restart

**Comment by Whizyyy** [comment]
Hey, thanks for reporting!

Please try with the new version.
